export const PLUGIN_NAME = "わんコメ麻雀プラグイン"
export const PLUGIN_UID = "net.yuarasino.onecomme-mahjong-plugin"
export const PLUGIN_VERSION = "1.0.0"
export const PLUGIN_AUTHOR = "新篠ゆう"
export const PLUGIN_URL = "https://github.com/yuarasino/onecomme-mahjong-plugin"
